apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world
spec:
  results:
    - name: message
      value: $(tasks.generate-hello-world.results.message)
  tasks:
    - name: generate-hello-world
      taskSpec:
        results:
          - name: message
        steps:
          - name: generate-message
            image: alpine
            script: |
              echo -n "Hello World!" > $(results.message.path)
---
apiVersion: tekton.dev/v1alpha1
kind: Run
metadata:
  generateName: piprun-
spec:
  ref:
    apiVersion: tekton.dev/v1beta1
    kind: Pipeline
    name: hello-world
